#!/bin/bash
# ═══════════════════════════════════════════════════════════════
# Vercel 빌드 스크립트
# ───────────────────────────────────────────────────────────────
# Vercel 환경변수 (SUPABASE_URL, SUPABASE_ANON_KEY) 값을
# env.js 파일에 주입하는 역할
# ═══════════════════════════════════════════════════════════════

echo "🔧 Building env.js with Vercel environment variables..."

cat > env.js << EOF
// Auto-generated by build.sh at Vercel build time
window.ENV = {
  SUPABASE_URL: '${SUPABASE_URL}',
  SUPABASE_ANON_KEY: '${SUPABASE_ANON_KEY}'
};
EOF

echo "✓ env.js generated"

# 값이 비어있으면 경고
if [ -z "$SUPABASE_URL" ] || [ -z "$SUPABASE_ANON_KEY" ]; then
  echo "⚠ WARNING: Supabase 환경변수가 비어있어요"
  echo "   Vercel Dashboard → Settings → Environment Variables 에서"
  echo "   SUPABASE_URL 과 SUPABASE_ANON_KEY 를 설정해주세요"
fi
